### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [ghaststeam/PS4EMX#38]
>

**Comment by andreas-hartmann** [comment]
Doesn't matter, hasn't been updated in years, so whether it was intended as a real project or not, it's dead.

**Comment by andreas-hartmann** [comment]
It's certainly "fake" in the sense that it can't execute anything. The code is not much more than placeholders.

**Comment by IIWare** [comment]
@Yugen42 thanks for telling me, and I just saw a bitrain video saying that the bios file is just filled with dots, and other ways that it's fake.
